const MessageType = {
  START_APP: 'START_APP',
  STOP_APP_REQUEST: 'STOP_APP_REQUEST',
  STOP_APP: 'STOP_APP',
  SCREENSHOT_DATA: 'SCREENSHOT_DATA',
  SCREENSHOT_REQUEST: 'SCREENSHOT_REQUEST',
};

export default MessageType;
